#!/bin/bash

set -e

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi

json=$(cat ../config.json)
docker_user=$(echo "$json" | jq -r '.source.docker_user')
docker_repo=$(echo "$json" | jq -r '.source.docker_repo')

source "$(dirname $0)/build.sh"

echo $json | docker run \
  -i \
  --rm \
  -v $source:/tmp/input \
  "${docker_user}/${docker_repo}" \
  /opt/resource/out /tmp/input/
