#!/bin/sh

# Resource Impl: http://concourse.ci/implementing-resources.html#out:-update-a-resource.
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi
#######################################

# parse incoming config data
payload=`cat`
bucket=$(echo "$payload" | jq -r '.source.bucket')
directory=$(echo "$payload" | jq -r '.source.directory // ""')
path=$(echo "$payload" | jq -r '.source.path // ""')
options=$(echo "$payload" | jq -r '.source.options // [] | join(" ")')

# export for `aws` cli
AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id // empty')
AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key // empty')
AWS_DEFAULT_REGION=$(echo "$payload" | jq -r '.source.region // empty')

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
fi

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

# Sync the source directory, if directory is unset
sync_path=$source
if [ -n "$directory" ]; then
  sync_path="$source/$directory"
fi

echo "Uploading to S3..."
eval aws s3 sync $sync_path "s3://$bucket/$path" $options
echo "...done."

# Output Link to Coverage Report
prefix="index.html"
if [ -n "$path" ]; then
  prefix="$path/index.html"
fi

index_versions=$(aws s3api list-object-versions --bucket $bucket --prefix ${prefix})
version_id=$(echo $index_versions | jq -r '.Versions[0].VersionId')
key=$(echo $index_versions | jq -r '.Versions[0].Key')
url="https://s3-$AWS_DEFAULT_REGION.amazonaws.com/$bucket/$key?versionId=$version_id"

echo "{
  \"version\": {\"version_id\": \"$version_id\"},
  \"metadata\": [{\"name\":\"Simplecov report url:\",\"value\": \"$url\"}]
}" >&3